#sudo docker image pull rustdesk/rustdesk-server
#sudo docker run --name hbbs -p 21115:21115 -p 21116:21116 -p 21116:21116/udp -p 21118:21118 -v `pwd`:/root -td --net=host rustdesk/rustdesk-server hbbs -r <relay-server-ip[:port]>
#sudo docker run --name hbbr -p 21117:21117 -p 21119:21119 -v `pwd`:/root -td --net=host rustdesk/rustdesk-server hbbr

version: '3'
services:
  nas-tasks:
    image: whyour/qinglong:latest
    container_name: "nas-tasks"
    restart: on-failure:3
    labels: 
     - "traefik.enable=true"
     - "traefik.http.routers.nas-task.entrypoints=web"
     - "traefik.http.services.nas-task.loadbalancer.server.port=5700"
     - "traefik.http.routers.nas-task.rule=Host(`tasks.$HOSTNAME`)"
    expose:
      - 9000
    entrypoint: "/ql/docker/docker-entrypoint.sh"
    volumes:
      - ${NAS_DOCKER_RUN_LOCATION}/run/nas-config/qinglong/:/ql/data/
      - ${NAS_DOCKER_RUN_LOCATION}/run/nas-log/qinglong:/ql/data/log/
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
